openapi: 3.0.0
info:
  title: Alpha Vantage
  description: >-
    API Documentation for Alpha Vantage. Alpha Vantage offers free JSON APIs for
    realtime and historical stock market data & options data with ...
  version: 1.0.0
servers:
  - url: http://{{baseurl}}
paths:
  /query:
    get:
      tags:
        - default
      summary: Sector Performance
      description: >-
        This API returns the realtime and historical sector performances
        calculated from S&P500 incumbents.
      parameters:
        - name: function
          in: query
          schema:
            type: string
          example: SECTOR
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
